### ISSUE TITLE
Chao race checks defaults to invalid option "high"

### ISSUE THREAD

**Issue by mayor-wren** [FelicitusNeko/archipelago-settings#2]
For the SA2 settings, the default option for chao race checks is "high" but the valid options are "prize" and "all". YAML files with "high" can cause game generation to fail.

https://github.com/FelicitusNeko/archipelago-settings/blob/8aa1ef4c3e051de8279cc25e1358ae66e572802b/src/defs/categories/021-sa2b.json#L114

**Comment by FelicitusNeko** [comment]
Thanks for the report. This has now been fixed and will be live shortly.
